# -*- coding: utf-8 -*-
"""VGGish_extraction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XtWzIGCPrhkbIQs3Q6_fGlp3Di1e1_tB
"""

#!/usr/bin/env python3
"""
VGGish Feature Extraction Script

This script extracts VGGish embeddings from an arbitrary audio dataset
(directory of .wav files).

Source: https://github.com/tensorflow/models/tree/master/research/audioset/vggish
"""

import os
import argparse
import numpy as np
import librosa
import tensorflow as tf

# VGGish imports (must be available in repo or PYTHONPATH)
import vggish_input
import vggish_params
import vggish_slim
import vggish_postprocess


def extract_vggish_embeddings(
    audio_path,
    sess,
    features_tensor,
    embedding_tensor
):
    """
    Extract VGGish embeddings from a single audio file.
    """
    # Convert audio to log-mel examples (same as original code)
    examples_batch = vggish_input.wavfile_to_examples(audio_path)

    if examples_batch is None or len(examples_batch) == 0:
        return None

    [embeddings] = sess.run(
        [embedding_tensor],
        feed_dict={features_tensor: examples_batch}
    )

    return embeddings


def process_dataset(input_dir, output_dir, checkpoint_path, pca_params_path):
    """
    Process all .wav files in input_dir and save VGGish embeddings.
    """
    os.makedirs(output_dir, exist_ok=True)

    with tf.Graph().as_default(), tf.compat.v1.Session() as sess:
        # Define VGGish model
        features_tensor = tf.compat.v1.placeholder(
            tf.float32,
            shape=(None, vggish_params.NUM_FRAMES, vggish_params.NUM_BANDS),
            name="input_features"
        )

        embedding_tensor = vggish_slim.define_vggish_slim(features_tensor)

        # Load checkpoint
        vggish_slim.load_vggish_slim_checkpoint(sess, checkpoint_path)

        # PCA postprocessor (same as original)
        pproc = vggish_postprocess.Postprocessor(pca_params_path)

        for root, _, files in os.walk(input_dir):
            for fname in files:
                if not fname.lower().endswith(".wav"):
                    continue

                audio_path = os.path.join(root, fname)
                print(f"Processing: {audio_path}")

                try:
                    embeddings = extract_vggish_embeddings(
                        audio_path,
                        sess,
                        features_tensor,
                        embedding_tensor
                    )

                    if embeddings is None:
                        print(f"Skipping (no embeddings): {audio_path}")
                        continue

                    # Postprocess embeddings
                    postprocessed_embeddings = pproc.postprocess(embeddings)

                    out_name = os.path.splitext(fname)[0] + ".npy"
                    out_path = os.path.join(output_dir, out_name)

                    np.save(out_path, postprocessed_embeddings)

                except Exception as e:
                    print(f"Error processing {audio_path}: {e}")


def main():
    parser = argparse.ArgumentParser(
        description="Extract VGGish embeddings from an audio dataset"
    )
    parser.add_argument(
        "--input_dir",
        type=str,
        required=True,
        help="Directory containing .wav audio files"
    )
    parser.add_argument(
        "--output_dir",
        type=str,
        required=True,
        help="Directory to save extracted embeddings (.npy)"
    )
    parser.add_argument(
        "--vggish_checkpoint",
        type=str,
        required=True,
        help="Path to vggish_model.ckpt"
    )
    parser.add_argument(
        "--pca_params",
        type=str,
        required=True,
        help="Path to vggish_pca_params.npz"
    )

    args = parser.parse_args()

    process_dataset(
        input_dir=args.input_dir,
        output_dir=args.output_dir,
        checkpoint_path=args.vggish_checkpoint,
        pca_params_path=args.pca_params
    )


if __name__ == "__main__":
    main()